-- Maintenance Copilot - initial Supabase schema
--
-- Run this file once in Supabase Dashboard -> SQL Editor. It is safe to run
-- again: tables and indexes are created conditionally, and project-owned
-- functions/triggers are replaced deliberately.

begin;

create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_trgm with schema extensions;

-- ---------------------------------------------------------------------------
-- Shared helpers

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Structured HPD taxonomy (loaded from the grouped CSV in a later step)

create table if not exists public.hpd_taxonomy (
  id bigint generated by default as identity primary key,
  major_category text not null,
  minor_category text not null default '',
  problem_code text not null,
  raw_type text not null,
  urgency text not null,
  complaint_count bigint not null default 0,
  search_text text generated always as (
    lower(
      coalesce(major_category, '') || ' ' ||
      coalesce(minor_category, '') || ' ' ||
      coalesce(problem_code, '')
    )
  ) stored,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint hpd_taxonomy_raw_type_check check (
    raw_type in ('IMMEDIATE EMERGENCY', 'EMERGENCY', 'HAZARDOUS', 'NON EMERGENCY')
  ),
  constraint hpd_taxonomy_urgency_check check (
    urgency in ('EMERGENCY', 'URGENT', 'ROUTINE')
  ),
  constraint hpd_taxonomy_count_check check (complaint_count >= 0),
  constraint hpd_taxonomy_source_row_unique unique (
    major_category, minor_category, problem_code, raw_type
  )
);

create index if not exists hpd_taxonomy_search_text_trgm_idx
  on public.hpd_taxonomy using gin (search_text extensions.gin_trgm_ops);

create index if not exists hpd_taxonomy_problem_code_idx
  on public.hpd_taxonomy (problem_code);

create index if not exists hpd_taxonomy_urgency_count_idx
  on public.hpd_taxonomy (urgency, complaint_count desc);

drop trigger if exists hpd_taxonomy_set_updated_at on public.hpd_taxonomy;
create trigger hpd_taxonomy_set_updated_at
before update on public.hpd_taxonomy
for each row execute function public.set_updated_at();

-- Fuzzy structured search used by the taxonomy tool. The table is small
-- (641 source rows), so ordering all rows by trigram similarity is predictable
-- and avoids returning no candidates for vague tenant language.
create or replace function public.search_hpd_taxonomy(
  query_text text,
  match_count integer default 5
)
returns table (
  id bigint,
  major_category text,
  minor_category text,
  problem_code text,
  raw_type text,
  urgency text,
  complaint_count bigint,
  similarity_score real
)
language sql
stable
security invoker
set search_path = public, extensions
as $$
  select
    taxonomy.id,
    taxonomy.major_category,
    taxonomy.minor_category,
    taxonomy.problem_code,
    taxonomy.raw_type,
    taxonomy.urgency,
    taxonomy.complaint_count,
    extensions.similarity(
      taxonomy.search_text,
      lower(trim(query_text))
    )::real as similarity_score
  from public.hpd_taxonomy as taxonomy
  where query_text is not null
    and trim(query_text) <> ''
  order by
    extensions.similarity(taxonomy.search_text, lower(trim(query_text))) desc,
    taxonomy.complaint_count desc,
    taxonomy.id
  limit greatest(1, least(coalesce(match_count, 5), 20));
$$;

-- ---------------------------------------------------------------------------
-- Durable case state and the exact conversation/agent audit trail

create table if not exists public.cases (
  id uuid primary key default gen_random_uuid(),
  public_id text not null unique default (
    'MC-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))
  ),
  status text not null default 'new',
  channel text not null default 'portal',
  unit text,
  summary text,
  issue_category text,
  problem_code text,
  urgency text,
  vendor_trade text,
  safety_flag boolean not null default false,
  safety_reason text,
  missing_info jsonb not null default '[]'::jsonb,
  offered_slots jsonb not null default '[]'::jsonb,
  appointment jsonb,
  citations jsonb not null default '[]'::jsonb,
  escalation_reason text,
  current_response text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint cases_status_check check (
    status in ('new', 'needs_info', 'awaiting_tenant', 'scheduled', 'escalated', 'resolved')
  ),
  constraint cases_channel_check check (
    channel in ('whatsapp', 'sms', 'email', 'portal')
  ),
  constraint cases_urgency_check check (
    urgency is null or urgency in ('EMERGENCY', 'URGENT', 'ROUTINE')
  ),
  constraint cases_missing_info_array_check check (jsonb_typeof(missing_info) = 'array'),
  constraint cases_offered_slots_array_check check (jsonb_typeof(offered_slots) = 'array'),
  constraint cases_citations_array_check check (jsonb_typeof(citations) = 'array'),
  constraint cases_metadata_object_check check (jsonb_typeof(metadata) = 'object')
);

create index if not exists cases_status_updated_at_idx
  on public.cases (status, updated_at desc);

drop trigger if exists cases_set_updated_at on public.cases;
create trigger cases_set_updated_at
before update on public.cases
for each row execute function public.set_updated_at();

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.cases(id) on delete cascade,
  role text not null,
  content text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint messages_role_check check (
    role in ('system', 'user', 'assistant', 'tool')
  ),
  constraint messages_content_check check (length(trim(content)) > 0)
);

create index if not exists messages_case_created_at_idx
  on public.messages (case_id, created_at, id);

create table if not exists public.case_events (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.cases(id) on delete cascade,
  step_number integer not null,
  module text not null,
  event_type text not null,
  prompt jsonb,
  response jsonb,
  detail text,
  model text,
  token_usage jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint case_events_step_check check (step_number > 0),
  constraint case_events_prompt_object_check check (
    prompt is null or jsonb_typeof(prompt) = 'object'
  ),
  constraint case_events_token_usage_object_check check (
    token_usage is null or jsonb_typeof(token_usage) = 'object'
  ),
  constraint case_events_case_step_unique unique (case_id, step_number)
);

create index if not exists case_events_case_step_idx
  on public.case_events (case_id, step_number);

-- Allocate a per-case step number under a row lock so simultaneous requests
-- cannot create duplicate trace positions.
create or replace function public.append_case_event(
  p_case_id uuid,
  p_module text,
  p_event_type text,
  p_prompt jsonb default null,
  p_response jsonb default null,
  p_detail text default null,
  p_model text default null,
  p_token_usage jsonb default null
)
returns public.case_events
language plpgsql
security invoker
set search_path = public
as $$
declare
  next_step integer;
  inserted_event public.case_events;
begin
  perform 1 from public.cases where id = p_case_id for update;
  if not found then
    raise exception 'Case % does not exist', p_case_id using errcode = '23503';
  end if;

  select coalesce(max(step_number), 0) + 1
    into next_step
    from public.case_events
   where case_id = p_case_id;

  insert into public.case_events (
    case_id, step_number, module, event_type, prompt, response,
    detail, model, token_usage
  ) values (
    p_case_id, next_step, p_module, p_event_type, p_prompt, p_response,
    p_detail, p_model, p_token_usage
  )
  returning * into inserted_event;

  return inserted_event;
end;
$$;

-- ---------------------------------------------------------------------------
-- RAG ingestion manifest. Pinecone stores the vectors; Supabase stores the
-- auditable source/chunk inventory and source authority.

create table if not exists public.rag_documents (
  id text primary key,
  source_name text not null,
  source_type text not null,
  title text not null,
  file_name text not null,
  version text,
  content_sha256 text not null,
  authority_rank smallint not null default 100,
  page_count integer,
  metadata jsonb not null default '{}'::jsonb,
  ingested_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rag_documents_source_type_check check (
    source_type in ('law', 'official_guidance', 'operational_guidance', 'internal_playbook')
  ),
  constraint rag_documents_hash_check check (content_sha256 ~ '^[0-9a-f]{64}$'),
  constraint rag_documents_rank_check check (authority_rank > 0),
  constraint rag_documents_page_count_check check (page_count is null or page_count > 0),
  constraint rag_documents_metadata_object_check check (jsonb_typeof(metadata) = 'object')
);

drop trigger if exists rag_documents_set_updated_at on public.rag_documents;
create trigger rag_documents_set_updated_at
before update on public.rag_documents
for each row execute function public.set_updated_at();

create table if not exists public.rag_chunks (
  id text primary key,
  document_id text not null references public.rag_documents(id) on delete cascade,
  pinecone_namespace text not null,
  chunk_index integer not null,
  page_start integer,
  page_end integer,
  section text,
  content_sha256 text not null,
  text_content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint rag_chunks_chunk_index_check check (chunk_index >= 0),
  constraint rag_chunks_page_start_check check (page_start is null or page_start > 0),
  constraint rag_chunks_page_end_check check (page_end is null or page_end > 0),
  constraint rag_chunks_page_order_check check (
    page_start is null or page_end is null or page_end >= page_start
  ),
  constraint rag_chunks_hash_check check (content_sha256 ~ '^[0-9a-f]{64}$'),
  constraint rag_chunks_text_check check (length(trim(text_content)) > 0),
  constraint rag_chunks_metadata_object_check check (jsonb_typeof(metadata) = 'object'),
  constraint rag_chunks_document_index_unique unique (document_id, chunk_index)
);

create index if not exists rag_chunks_document_idx
  on public.rag_chunks (document_id, chunk_index);

create index if not exists rag_chunks_namespace_idx
  on public.rag_chunks (pinecone_namespace);

-- ---------------------------------------------------------------------------
-- Scheduling foundation. These tables replace generated browser-only slots in
-- the later scheduling-tool step; this migration intentionally does not seed
-- fictional vendors or claim any real notification has occurred.

create table if not exists public.vendors (
  id text primary key,
  name text not null,
  trade text not null,
  approved boolean not null default false,
  active boolean not null default true,
  email text,
  phone text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint vendors_metadata_object_check check (jsonb_typeof(metadata) = 'object')
);

create index if not exists vendors_trade_approved_idx
  on public.vendors (trade, approved, active);

drop trigger if exists vendors_set_updated_at on public.vendors;
create trigger vendors_set_updated_at
before update on public.vendors
for each row execute function public.set_updated_at();

create table if not exists public.vendor_slots (
  id uuid primary key default gen_random_uuid(),
  vendor_id text not null references public.vendors(id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'available',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint vendor_slots_time_check check (ends_at > starts_at),
  constraint vendor_slots_status_check check (
    status in ('available', 'held', 'booked', 'cancelled')
  ),
  constraint vendor_slots_metadata_object_check check (jsonb_typeof(metadata) = 'object'),
  constraint vendor_slots_vendor_window_unique unique (vendor_id, starts_at, ends_at)
);

create index if not exists vendor_slots_trade_time_idx
  on public.vendor_slots (vendor_id, status, starts_at);

drop trigger if exists vendor_slots_set_updated_at on public.vendor_slots;
create trigger vendor_slots_set_updated_at
before update on public.vendor_slots
for each row execute function public.set_updated_at();

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  slot_id uuid not null references public.vendor_slots(id),
  vendor_id text not null references public.vendors(id),
  status text not null default 'booked',
  confirmation_data jsonb not null default '{}'::jsonb,
  booked_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint appointments_status_check check (
    status in ('booked', 'confirmed', 'completed', 'cancelled')
  ),
  constraint appointments_confirmation_object_check check (
    jsonb_typeof(confirmation_data) = 'object'
  ),
  constraint appointments_case_unique unique (case_id),
  constraint appointments_slot_unique unique (slot_id)
);

create index if not exists appointments_vendor_booked_at_idx
  on public.appointments (vendor_id, booked_at desc);

drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at
before update on public.appointments
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Security: the public UI never talks to Supabase directly. RLS is enabled and
-- no anon/authenticated policies are created. The backend secret key assumes
-- service_role and is the only application credential allowed to access data.

alter table public.hpd_taxonomy enable row level security;
alter table public.cases enable row level security;
alter table public.messages enable row level security;
alter table public.case_events enable row level security;
alter table public.rag_documents enable row level security;
alter table public.rag_chunks enable row level security;
alter table public.vendors enable row level security;
alter table public.vendor_slots enable row level security;
alter table public.appointments enable row level security;

revoke all on function public.search_hpd_taxonomy(text, integer)
  from public, anon, authenticated;
grant execute on function public.search_hpd_taxonomy(text, integer)
  to service_role;

revoke all on function public.append_case_event(
  uuid, text, text, jsonb, jsonb, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.append_case_event(
  uuid, text, text, jsonb, jsonb, text, text, jsonb
) to service_role;

commit;
